spring:
    datasource:
        url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/issuedb}
        username: ${JDBC_DATABASE_USERNAME:postgres}
        password: ${JDBC_DATABASE_PASSWORD:root}
        maxActive: 10
        maxIdle: 5
        minIdle: 2
        initialSize: 5
        removeAbandoned: true
    jpa:
        properties.hibernate:
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hibernate:
            ddl-auto: validate
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/main.xml
